# Generated by Django 4.2.7 on 2025-12-25 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_movie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Kino', 'verbose_name_plural': 'Kinolar'},
        ),
        migrations.AddField(
            model_name='movie',
            name='is_series',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='app.movie')),
            ],
            options={
                'verbose_name': 'Qism',
                'verbose_name_plural': 'Qismlar',
                'ordering': ['number'],
            },
        ),
    ]
