# Generated by Django 4.2.7 on 2025-12-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_movie_options_movie_is_series_movie_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
